<a href="https://colab.research.google.com/github/XJTellez/X-ray-diffraction/blob/main/XR_diffraction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Difracción de rayos X.

In [1]:
# Primero se llaman las bibliotecas a utilizar
import numpy as np

In [2]:
# Se ingresan los valores de 2 theta ((valores separados por coma))
dos_theta = np.array((42.8, 73.2, 89.0,115.0))

In [3]:
# Se verifican los datos ingresados
dos_theta 

array([ 42.8,  73.2,  89. , 115. ])

In [4]:
# Se obtiene theta.
theta = dos_theta/2.0

# Se verifican los valores de theta
theta

array([21.4, 36.6, 44.5, 57.5])

In [5]:
# Se convierte theta a radianes
theta_rad = 2.0*np.pi*theta/360.
theta_rad

array([0.37350046, 0.63879051, 0.77667152, 1.00356432])

In [6]:
# Se cacula el sen^2 theta
sen_quad = np.sin(theta_rad)**2.0

# Se imprime el valor
sen_quad

array([0.13313507, 0.3554841 , 0.4912738 , 0.71130913])

In [8]:
# Para el ángulo minimo
theta_rad[0]

0.3735004599267865

In [9]:
# Se calcula el sen^2 theta/ sen^2 theta min
# El theta min corresponde al primer elemento del arreglo.
sen_sen_min = np.sin(theta_rad)**2.0/np.sin(theta_rad[0])**2.0

# Se imprime el valor
sen_sen_min

array([1.        , 2.67010118, 3.69004054, 5.34276313])

In [10]:
# Se multiplica el resultado anterior por dos
dos_sen_sen_min = 2.*sen_sen_min

# Se imprime el valor
dos_sen_sen_min

array([ 2.        ,  5.34020236,  7.38008107, 10.68552625])

In [11]:
# Se multiplica el resultado anterior por tres
tres_sen_sen_min = 3.*sen_sen_min

# Se imprime el valor
tres_sen_sen_min

array([ 3.        ,  8.01030354, 11.07012161, 16.02828938])

In [13]:
# Se redondea al entero más próximo para obtener s
s = np.round(tres_sen_sen_min)

# Imprime s
s

array([ 3.,  8., 11., 16.])

In [15]:
# Se guardan h, k, l.
h = np.array((1,2,3,4))
k = np.array((1,2,1,0))
l = np.array((1,0,1,0))

In [16]:
# Se elevan al cuadrado
hh = h**2.0
kk = k**2.0
ll = l**2.0

In [19]:
# Se asigna el valor de la longitud de onda 
long = 1.5

In [20]:
# Se calcula el factor de escala.
a = np.sqrt(long**2.0*(hh + kk + ll)/(4.0*sen_quad))
a

array([3.56021035, 3.55791989, 3.5489167 , 3.55706714])

In [22]:
# Para acomodar los datos obtenidos en una tabla se necesita la biblioteca siguiente
import pandas as pd

In [26]:
# El arreglo nos da el número de picos
# Dependiendo del número de ángulos considerados al inicio

# Se guardan los números
n = []

# El for irá ingresando los valores
for i in range(len(theta_rad)):
  n.append(i+1)

# Se verifican los valores
n

[1, 2, 3, 4]

In [30]:
# Se realiza la tabla
df = pd.DataFrame(
    {
        "n" : n,                                              # número de picos
        "2theta": dos_theta,                                  # dos theta
        "sin^2(theta)": sen_quad,                              # seno cuadrado del ángulo
        "sin^2(theta)/sin^2(theta_min)" : sen_sen_min,          #seno cuadrado del ángulo entre seno cuadrado del angulo mínimo
        "2 x sin^2(theta)/sin^2(theta_min)" : dos_sen_sen_min,  # dos veces el resultado anterior
        "3 x sin^2(theta)/sin^2(theta_min)" : tres_sen_sen_min, #tres veces el resultado anterior.
        "s" : s,                                              # s
        "h" : h,                                              # h
        "k" : k,                                              # k
        "l" : l,                                              # l
        "a" : a,                                              # factor de escala
    }
)

In [31]:
# Se imprime la tabla de resultados
df

n  2theta  sin^2(theta)  sin^2(theta)/sin^2(theta_min)  \
0  1    42.8      0.133135                       1.000000   
1  2    73.2      0.355484                       2.670101   
2  3    89.0      0.491274                       3.690041   
3  4   115.0      0.711309                       5.342763   

   2 x sin^2(theta)/sin^2(theta_min)  3 x sin^2(theta)/sin^2(theta_min)     s  \
0                           2.000000                           3.000000   3.0   
1                           5.340202                           8.010304   8.0   
2                           7.380081                          11.070122  11.0   
3                          10.685526                          16.028289  16.0   

   h  k  l         a  
0  1  1  1  3.560210  
1  2  2  0  3.557920  
2  3  1  1  3.548917  
3  4  0  0  3.557067